# Generated by Django 5.0.1 on 2024-01-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="banners/")),
                ("alt_text", models.CharField(max_length=150)),
            ],
        ),
    ]
