# Generated by Django 5.0.1 on 2024-01-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0002_banners"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="img",
            field=models.ImageField(null=True, upload_to="services/"),
        ),
    ]
