# Generated by Django 5.0.1 on 2024-01-20 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0007_gallery_galleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="gallery",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="swimming_app.gallery",
            ),
        ),
    ]
