# Generated by Django 5.0.1 on 2024-01-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0008_galleryimage_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SubPlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "subplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="swimming_app.subplan",
                    ),
                ),
            ],
        ),
    ]
