# Generated by Django 5.0.1 on 2024-01-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0009_subplan_subplanfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="subplan",
            name="highlight_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
