# Generated by Django 5.0.1 on 2024-01-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0011_remove_subplanfeature_subplan_subplanfeature_subplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="subplan",
            name="max_member",
            field=models.IntegerField(null=True),
        ),
    ]
