# Generated by Django 4.2.2 on 2024-02-02 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0014_subscriber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
