# Generated by Django 4.2.2 on 2024-02-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0016_subscription_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("detail", models.TextField()),
                ("img", models.ImageField(null=True, upload_to="trainers/")),
            ],
        ),
    ]
