# Generated by Django 4.2.2 on 2024-02-23 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0020_alter_notify_read_by_trainer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notify",
            name="status",
        ),
    ]
