# Generated by Django 4.2.2 on 2024-02-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0025_subscription_reg_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banners",
            options={"verbose_name_plural": "Banners"},
        ),
        migrations.AddField(
            model_name="trainer",
            name="facebook",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="pinterest",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="twitter",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="youtube",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
