# Generated by Django 4.2.2 on 2024-02-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0026_alter_banners_options_trainer_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="salary",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TrainerAchivement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("detail", models.TextField()),
                ("img", models.ImageField(upload_to="trainers_achivements/")),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="swimming_app.trainer",
                    ),
                ),
            ],
        ),
    ]
