# Generated by Django 4.2.2 on 2024-02-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0027_trainer_salary_trainerachivement"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amt", models.IntegerField()),
                ("amt_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="swimming_app.trainer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trainer Salary",
            },
        ),
    ]
