# Generated by Django 4.2.2 on 2024-02-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0028_trainersalary"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notif_msg", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="NotifTrainerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "notif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="swimming_app.trainernotification",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="swimming_app.trainer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trainer Notification Status",
            },
        ),
    ]
