# Generated by Django 4.2.2 on 2024-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming_app", "0031_trainersubscriberreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_img", models.ImageField(upload_to="app_logos/")),
            ],
        ),
    ]
